[project]
name = "llm-agents-lab"
version = "0.1.0"
description = "learning llm-agents"
readme = "README.md"
authors = [
    { name = "Breakdown08", email = "kirmish.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain[openai]>=1.4.2",
    "langgraph>=1.2.12",
    "python-dotenv>=1.2.3",
]

[project.scripts]
project = "llm_agents_lab.main:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
